/*
Copyright (c) 2025 ZEISS Group, Sebastian Doell (@katallaxie)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	sourcesv1alpha1 "github.com/zeiss/zeiss/knative-extension-sample-source/pkg/apis/sources/v1alpha1"
	scheme "github.com/zeiss/zeiss/knative-extension-sample-source/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SampleSourcesGetter has a method to return a SampleSourceInterface.
// A group's client should implement this interface.
type SampleSourcesGetter interface {
	SampleSources(namespace string) SampleSourceInterface
}

// SampleSourceInterface has methods to work with SampleSource resources.
type SampleSourceInterface interface {
	Create(ctx context.Context, sampleSource *sourcesv1alpha1.SampleSource, opts v1.CreateOptions) (*sourcesv1alpha1.SampleSource, error)
	Update(ctx context.Context, sampleSource *sourcesv1alpha1.SampleSource, opts v1.UpdateOptions) (*sourcesv1alpha1.SampleSource, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, sampleSource *sourcesv1alpha1.SampleSource, opts v1.UpdateOptions) (*sourcesv1alpha1.SampleSource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*sourcesv1alpha1.SampleSource, error)
	List(ctx context.Context, opts v1.ListOptions) (*sourcesv1alpha1.SampleSourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *sourcesv1alpha1.SampleSource, err error)
	SampleSourceExpansion
}

// sampleSources implements SampleSourceInterface
type sampleSources struct {
	*gentype.ClientWithList[*sourcesv1alpha1.SampleSource, *sourcesv1alpha1.SampleSourceList]
}

// newSampleSources returns a SampleSources
func newSampleSources(c *SourcesV1alpha1Client, namespace string) *sampleSources {
	return &sampleSources{
		gentype.NewClientWithList[*sourcesv1alpha1.SampleSource, *sourcesv1alpha1.SampleSourceList](
			"samplesources",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *sourcesv1alpha1.SampleSource { return &sourcesv1alpha1.SampleSource{} },
			func() *sourcesv1alpha1.SampleSourceList { return &sourcesv1alpha1.SampleSourceList{} },
		),
	}
}
