apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-source-controller
  labels:
    sources.eventing.zeiss.com/release: devel
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: &everything
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - list

- apiGroups:
  - ""
  resources:
  - events
  verbs: *everything

- apiGroups:
  - sources.eventing.zeiss.com
  resources:
  - samplesources
  verbs: *everything

- apiGroups:
  - sources.eventing.zeiss.com
  resources:
  - samplesources/status
  - samplesources/finalizers
  verbs:
  - get
  - update
  - patch

- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list

- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch

  # For Leader Election
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs: *everything

---
# The role is needed for the aggregated role source-observer in knative-eventing to provide readonly access to "Sources".
# See https://github.com/knative/eventing/blob/master/config/200-source-observer-clusterrole.yaml.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sample-source-observer
  labels:
    sources.eventing.zeiss.com/release: devel
    duck.knative.dev/source: "true"
rules:
  - apiGroups:
      - "sources.eventing.zeiss.com"
    resources:
      - "samplesources"
    verbs:
      - get
      - list
      - watch
