apiVersion: v1
kind: Service
metadata:
  labels:
    sources.eventing.zeiss.com/release: devel
    control-plane: sample-source-controller-manager
  name: sample-source-controller-manager
  namespace: knative-samples
spec:
  selector:
    control-plane: sample-source-controller-manager
  ports:
  - port: 443
