apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.webhook.sources-samples.sources.eventing.zeiss.com
  labels:
    sources.eventing.zeiss.com/release: devel
webhooks:
  - admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: sample-source-webhook
        namespace: sources-samples
    sideEffects: None
    failurePolicy: Fail
    name: defaulting.webhook.sources-samples.sources.eventing.zeiss.com
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.sources-samples.sources.eventing.zeiss.com
  labels:
    sources.eventing.zeiss.com/release: devel
webhooks:
  - admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: sample-source-webhook
        namespace: sources-samples
    sideEffects: None
    failurePolicy: Fail
    name: validation.webhook.sources-samples.sources.eventing.zeiss.com
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.webhook.sources-samples.sources.eventing.zeiss.com
  labels:
    sources.eventing.zeiss.com/release: devel
webhooks:
  - admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: sample-source-webhook
        namespace: sources-samples
    sideEffects: None
    failurePolicy: Fail
    name: config.webhook.sources-samples.sources.eventing.zeiss.com
    namespaceSelector:
      matchExpressions:
        - key: sources.eventing.zeiss.com/release
          operator: Exists
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: sources-samples
  labels:
    sources.eventing.zeiss.com/release: devel
# The data is populated at install time.
