apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-source-webhook
  namespace: sources-samples
  labels:
    sources.eventing.zeiss.com/release: devel
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: sample-source-webhook
      role: sample-source-webhook
  template:
    metadata:
      labels: *labels
    spec:
      # To avoid node becoming SPOF, spread our replicas to different nodes.
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: sample-source-webhook
              topologyKey: kubernetes.io/hostname
            weight: 100

      serviceAccountName: sample-source-webhook
      containers:
        - name: sample-source-webhook
          terminationMessagePolicy: FallbackToLogsOnError
          image: ko://github.com/zeiss/knative-extension-sample-source/cmd/webhook
          env:
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONFIG_LOGGING_NAME
            value: config-logging
          - name: METRICS_DOMAIN
            value: knative.dev/eventing
          - name: WEBHOOK_NAME
            value: sample-source-webhook
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          ports:
          - containerPort: 9090
            name: metrics
          readinessProbe: &probe
            periodSeconds: 1
            httpGet:
              scheme: HTTPS
              port: 8443
              httpHeaders:
              - name: k-kubelet-probe
                value: "webhook"
          livenessProbe: *probe

---

apiVersion: v1
kind: Service
metadata:
  labels:
    sources.eventing.zeiss.com/release: devel
    role: sample-source-webhook
  name: sample-source-webhook
  namespace: sources-samples
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    role: sample-source-webhook
