apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-source-controller
  namespace: knative-samples
  labels:
    sources.eventing.zeiss.com/release: devel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-source-controller
  template:
    metadata:
      labels:
        app: sample-source-controller
        sources.eventing.zeiss.com/release: devel
    spec:
      # To avoid node becoming SPOF, spread our replicas to different nodes.
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: sample-source-controller
              topologyKey: kubernetes.io/hostname
            weight: 100

      serviceAccountName: sample-source-controller

      containers:
      - name: controller
        terminationMessagePolicy: FallbackToLogsOnError
        image: ko://github.com/zeiss/knative-extension-sample-source/cmd/controller

        resources:
          requests:
            cpu: 100m
            memory: 100Mi

        env:
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONFIG_LOGGING_NAME
            value: config-logging
          - name: CONFIG_OBSERVABILITY_NAME
            value: config-observability
          - name: METRICS_DOMAIN
            value: knative.dev/sources
          - name: SAMPLE_SOURCE_RA_IMAGE
            value: ko://github.com/zeiss/knative-extension-sample-source/cmd/receive_adapter
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

        securityContext:
          allowPrivilegeEscalation: false

        ports:
          - name: metrics
            containerPort: 9090
